### ISSUE TITLE
authorization not happening!!

### ISSUE THREAD

**Issue by diepolkovnik** [vakochetkov/aiowc#1] opened 2022-05-15 00:14 UTC
![image](https://user-images.githubusercontent.com/31825841/168452134-dacca117-65d1-4d4e-9c64-09469a3854d8.png)
![image](https://user-images.githubusercontent.com/31825841/168452141-e894e623-d42e-451c-a022-d805abc5ea56.png)
on the standard library everything works fine.

**Comment by vakochetkov** [comment] 2022-05-15 18:38
I'll check. 
It'd be better do not place secrets (wcapi tokens) in public.
Probably you should re-generate your WooCommerce API key/secret.

**Comment by vakochetkov** [comment] 2022-05-15 18:50
The problem is you using [Basic Auth](https://woocommerce.github.io/woocommerce-rest-api-docs/v3.html#authentication) over HTTP as you paste "http://...." as url parameter in API instance.
You have to switch to https or use [OAuth 1.0a](http://tools.ietf.org/html/rfc5849) which aiowc does not support yet.
Perhaps you'd like to take a look at the sources of [sync library](https://github.com/woocommerce/wc-api-python/blob/trunk/woocommerce/oauth.py) for OAuth implementation.
I would probably add this feature to aiowc in the near future.

**Comment by vakochetkov** [comment] 2022-05-19 01:31
Fixed in 0.2.3 (switched to SemVer).
Please re-install aiowc - https://pypi.org/project/aiowc/

**Closed as completed by vakochetkov** 2022-05-19 01:31 UTC

**Comment by diepolkovnik** [comment] 2022-05-19 23:05
thank you so much, good luck with your development
